title = "Frostie blue cream â€” slightly unpleasant fake sweet flavour"
published = 2012-10-25T12:51:09Z
image = "https://mnf.m17s.net/2012/10/25/frostie-blue-cream-slightly-unpleasant-fake-sweet-flavour.jpg"
origin = "instagram"
type = "photo"

[thumbnail]
w200 = "https://mnf.m17s.net/2012/10/25/frostie-blue-cream-slightly-unpleasant-fake-sweet-flavour.200.jpg"
w80 = "https://mnf.m17s.net/2012/10/25/frostie-blue-cream-slightly-unpleasant-fake-sweet-flavour.80.jpg"
