published = 2015-08-07T19:46:53Z
title = "Checked in at Côte Brasserie"
type = "foursquare"
source = "Foursquare (Swarm)"
map = "https://mnf.m17s.net/maps/a4d968062fbac607e30648fad7a9fab891bbdfe8d4d76bde20cf1d301e8fece7.png"
local_timestamp = 2015-08-07T20:46:53Z

[data]
id = "55c4fd1d498efff7f65611ef"
createdAt = 1438973213
type = "checkin"
timeZoneOffset = 60

[data.venue]
id = "4b39011af964a5200b5425e3"
name = "Côte Brasserie"
[[data.venue.categories]]
id = "4bf58dd8d48988d10c941735"
name = "French Restaurant"
pluralName = "French Restaurants"
shortName = "French"
primary = true

[data.venue.categories.icon]
prefix = "https://ss3.4sqi.net/img/categories_v2/food/french_"
suffix = ".png"

[data.venue.location]
address = "47 Kensington Ct"
lat = 51.50209151556875
lng = -0.18889848304386928
postalCode = "W8 5DA"
cc = "GB"
neighborhood = "Queen's Gate"
city = "Kensington"
state = "Greater London"
country = "United Kingdom"
formattedAddress = [ "47 Kensington Ct", "Kensington", "Greater London", "W8 5DA",]
[[data.venue.location.labeledLatLngs]]
label = "display"
lat = 51.50209151556875
lng = -0.18889848304386928

