title = "Pop Shoppe cola â€” tastes like a flat, liquid cola bottle sweet; meh"
published = 2012-06-21T19:38:01Z
image = "https://mnf.m17s.net/2012/06/21/pop-shoppe-cola-tastes-like-a-flat-liquid-cola-bottle-sweet-meh.jpg"
origin = "instagram"
type = "photo"

[thumbnail]
w200 = "https://mnf.m17s.net/2012/06/21/pop-shoppe-cola-tastes-like-a-flat-liquid-cola-bottle-sweet-meh.200.jpg"
w80 = "https://mnf.m17s.net/2012/06/21/pop-shoppe-cola-tastes-like-a-flat-liquid-cola-bottle-sweet-meh.80.jpg"
