title = "Currently chargingâ€¦"
published = 2014-07-25T19:18:52Z
image = "https://mnf.m17s.net/2014/07/25/currently-charging.jpg"
origin = "instagram"
type = "photo"

[thumbnail]
w200 = "https://mnf.m17s.net/2014/07/25/currently-charging.200.jpg"
w80 = "https://mnf.m17s.net/2014/07/25/currently-charging.80.jpg"
