title = "LV-426 Hadley's Hope #daily #tshirt â€” the start of Aliens \"week\""
published = 2012-09-17T06:38:20Z
image = "https://mnf.m17s.net/2012/09/17/lv-426-hadleys-hope-daily-tshirt-the-start-of-aliens-week.jpg"
origin = "instagram"
type = "photo"
tag = [ "daily", "tshirt",]
