title = "What, when, where, why â€” reminders for my floor meeting announcement"
published = 2012-11-27T10:31:41Z
image = "https://mnf.m17s.net/2012/11/27/what-when-where-why-reminders-for-my-floor-meeting-announcement.jpg"
origin = "instagram"
type = "photo"
